### ISSUE TITLE
How to train the model

### ISSUE THREAD

**Issue by mmajhi** [anubhavs11/Fake-Product-Review-Monitoring#1]
If you provide the script through which you trained the model will be helpful. 

The pickle files which are used to get the output should be provided.

**Comment by anubhavs11** [comment]
You can find those codes here https://github.com/anubhavs11/Sentimental-Analysis-using-Logistic-Regression

**Comment by anubhavs11** [comment]
You can find those codes here https://github.com/anubhavs11/Sentimental-Analysis-using-Logistic-Regression
