### ISSUE TITLE
kindly address my issue related to fake product review monitoring

### ISSUE THREAD

**Issue by Hasnain950** [anubhavs11/Fake-Product-Review-Monitoring#4]
Hi Dear,
Anubhavs 
I go through all your work and specially your code. I am personally very inspired by your work and your efforts in this project. I was searching some codes related to fake review detection for a long time but when i saw your project i felt really happy because your code fulfills all my requirements but while running  your code i am facing some issues such as, Some files are missing!(pickle). I am also attaching a screenshot of the error being occurred.
I am desperately  waiting for your reply, I am pretty sure that you will help me as soon as possible by addressing my issue.
I shall be very thankful to you.
![Code](https://user-images.githubusercontent.com/85987516/122181348-b9abcd00-cea2-11eb-94e2-0d39f3fbedff.JPG)

**Comment by anubhavs11** [comment]
Hi,
I'm really sorry for seeing your post so late.

Here are the required files.
https://github.com/anubhavs11/Sentimental-Analysis-using-Logistic-Regression/tree/master/preserved%20files
